Sprint 1/step 2
andreyosintsev/react-burger pull request #3
Opened 2023-05-05 14:16 UTC by andreyosintsev

Добрый день. Прошу провести ревью для моей работы. Спасибо.

2023-05-06 06:56 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Записываете ошибку в стейт
- Есть отписка от слушателя событий
- Отличная работа с `propTypes`

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Добавьте проверку успешности запроса
- у ModalOverlay не должно быть children, это просто компонент подложки а не контейнер
- Файл App.test.tsx необходимо удалить - он не понадобится.

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-06 06:56 UTC, andryxxa93 commented on src/components/app/app.js
> +   const getIngredientsData = () => {
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-05-06 06:56 UTC, andryxxa93 commented on src/components/app/app.js
> +            return res.json();
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2023-05-06 06:56 UTC, andryxxa93 commented on src/components/modal-overlay/modal-overlay.js
> +function ModalOverlay({onclick, children}) {
**Надо исправить**

у ModalOverlay не должно быть children, это просто компонент подложки а не контейнер

2023-05-06 06:56 UTC, andryxxa93 commented on src/components/modal/modal.js
> +      document.removeEventListener('keydown', onEscDown);
**Отлично!**
Вы сделали отписку от слушателя, это позволит избежать утечек памяти.

2023-05-06 10:29 UTC, andreyosintsev commented
Добрый день.

Я внес правки, которые были помечены вами как "Необходимо исправить".

Однако у меня есть пара вопросов:

>>Файл App.test.tsx необходимо удалить - он не понадобится.
Прошу прощения, нигде не нашёл этот файл, ни у себя в проекте, ни в репозитории. Наверное, тут какая-то ошибка

>>В дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции
Это замечание было помечено как "Можно лучше", и я его не осилил.

У меня не получилось вынести функцию получения данных через  API в отдельный файл, потому что я не смог решить проблему с асинхронностью. Рекомендуемый файл utils/burger-api.js я создал, перенес туда функционал, но пока не использовал. Функция возвращает нулевой ответ до того, как выполнится fetch, насколько я понял, и что с этим делать я не знаю.

Благодарю за ревью, запушил новый коммит прямо в этот пул реквест, как вы и просили.

2023-05-07 05:30 UTC, andryxxa93 commented
**Необходимо исправить**
Вам нужно возвращать из `getIngredientsFromApi` промис -

```
const getIngredientsFromAPI = (api) => {
  try {
    return fetch(`${api}/ingredients`)
      .then(checkFetchResponse)
      .then((data) => {
        return data.data
      })
    );
  } catch (error) {
      throw new Error(`Ingredient data fetch error: ${error}`);
  }
};
```
А в `App` можно сделать так 
` getIngredientsFromAPI(NORMA_API).then(data => setState({...state, ingredientsData: data}));`


Поправьте этот момент и работа будет принята.

2023-05-07 11:17 UTC, andreyosintsev commented
Я внес необходимые правки. Надеюсь, теперь всё хорошо. Спасибо.

2023-05-07 16:45 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-07 18:54 UTC, merged