Sprint 2/step 1
andreyosintsev/react-burger pull request #5
Opened 2023-05-12 14:59 UTC by andreyosintsev

Добрый день. Прошу провести ревью моего кода и не судить строго. )

2023-05-12 15:19 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- В контекст обернуты только те компоненты, что будут его использовать
- Использовали два отдельных контекста
- Использовали useReducer

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Проект собирается с ошибкой - у вас неправильный импорт в `OrderDetails`

<img width="1013" alt="Снимок экрана 2023-05-12 в 18 13 29" src="https://github.com/andreyosintsev/react-burger/assets/60173362/c661da56-7ecc-4a33-8bdd-8aa86f127a4a">

- В консоли есть ошибка связанная с `propTypes`

<img width="446" alt="Снимок экрана 2023-05-12 в 18 18 32" src="https://github.com/andreyosintsev/react-burger/assets/60173362/abc269bf-17af-4f0a-a573-ffd9e09ecc5a">

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-12 15:19 UTC, andryxxa93 commented on src/utils/burger-api.js
> +              return method === 'get' ? data.data : data.order;
**Можно лучше**
В будущем запросов станет больше поэтому рекомендую делать отдельные функции запросы, иначе будет сложно поддерживать универсальный вариант как сейчас

2023-05-13 13:17 UTC, andreyosintsev commented
Добрый день.

Подскажите, как может быть так, что у меня проект собрался без ошибок (иначе я бы его не отправил на ревью), а у вас с ошибками? Причём уже не первый раз. Может быть где-то что-то кэшируется, и не пересобирается. Например история с неправильным импортом PropTypes - это были изменения в последний момент. Может быть так, что где-то в bundle.js попала непересобранная версия? И если так - как правильно поступать? Останавливать выполняющийся скрипт react-scripts start? Закрывать и заново открывать браузер? Может быть, сделать билд через react-scripts build? Хотелось бы избежать подобных проблем в будущем.

Указанные замечания поправил.

2023-05-14 05:25 UTC, andryxxa93 commented
> Добрый день.
> 
> Подскажите, как может быть так, что у меня проект собрался без ошибок (иначе я бы его не отправил на ревью), а у вас с ошибками? Причём уже не первый раз. Может быть где-то что-то кэшируется, и не пересобирается. Например история с неправильным импортом PropTypes - это были изменения в последний момент. Может быть так, что где-то в bundle.js попала непересобранная версия? И если так - как правильно поступать? Останавливать выполняющийся скрипт react-scripts start? Закрывать и заново открывать браузер? Может быть, сделать билд через react-scripts build? Хотелось бы избежать подобных проблем в будущем.
> 
> Указанные замечания поправил.

Проблема точно не в бандле. Возможно какие-то файлы не попадают в коммит сообщение.

2023-05-14 05:27 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-16 06:53 UTC, merged