Sprint 2/step 2
andreyosintsev/react-burger pull request #6
Opened 2023-05-26 06:17 UTC by andreyosintsev

Добрый день! Отправляю на ревью задание sprint-2/step-2. Спасибо!

2023-05-26 06:52 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Редьюсеры - чистые функции 
- Правильно настроен и работает `Dnd` 
- Для запросов созданы все необходимые типы экшенов

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- разделите редьюсер на несколько 
- Вынесите функции делающие запросы в экшены из редьюсеров
- Если добавить в конструктор разные ингредиенты по несколько раз, отсортировать их и потом начать удалять, то выскочит ошибка.

<img width="958" alt="Снимок экрана 2023-05-26 в 09 37 17" src="https://github.com/andreyosintsev/react-burger/assets/60173362/af572764-c012-4a4e-b338-55a84781b73e">

- В хранилище в `constructorList` и `constructorCounters` - содержат практически идентичную информацию - это не лучшая практика, дубликатов желательно избегать 

<img width="403" alt="Снимок экрана 2023-05-26 в 09 47 27" src="https://github.com/andreyosintsev/react-burger/assets/60173362/43161d2b-8d25-40cb-87a9-00804e521895">

Более подробно описание проблемы смотрите комментарии в pull request.

**Можно лучше**
-  лучше хранить в отдельном поле выбранную булку и в отдельном поле массив с начинками бургера, это сильно облегчит работу со стором в следущем этапе
`const constructorInitialState = { bun: null, ingredients: []};`

- желательно очищать конструктор после успешного получения номера заказа с сервера в блоке then, чтобы пользователь мог следующий заказ сделать, не удаляя старые ингредиенты
- лучше не давать нажать на кнопку Оформить заказ, пока пользователь не добавил булку в заказ.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-26 06:52 UTC, andryxxa93 commented on src/components/app/app.js
> +  const {
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-05-26 06:52 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.js
> +  let constructorList = useSelector(store => store.burgerConstructor.constructorList);
**Можно лучше**

**здесь и далее в других местах** если переменная не перезаписывается её нужно объявлять как `const`, это помогает понять другим разработчикам, как мы будем использовать переменную, будем ли мы в коде перезаписывать её значение.
Так же стоит помнить, что добавление элемента в массив или изменение свойства объект не являются перезаписью самой переменной, а только изменяют его внутренне состояние и такие переменные так же объявляются как const

2023-05-26 06:52 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.js
> +          <BurgerTotalContext.Provider value={sumState.sum}>
**Необходимо исправить**
Контекст необходимо удалить уже - вместо него нужно использовать `redux`

2023-05-26 06:52 UTC, andryxxa93 commented on src/services/reducers/burger-constructor.js
> +import { postConstructorDataToApi } from '../../utils/burger-api';
**Надо исправить**

со временем приложение будет разрастаться, появится новый функционал, если все будет в одном рельюсере он станет слишком большим, разделите один большой редьюсер на несколько, обрабатывающие данные одной предметной области (одного "домена"), например

- загрузка данных ингредиентов
- отправка заказа
- работа конструктора
- открытие модального окна ингредиента

Для объединения редьюсеров используйте combineReducers
https://redux.js.org/api/combinereducers

2023-05-26 06:52 UTC, andryxxa93 commented on src/services/reducers/burger-constructor.js
> +export const getOrderNumber = (data) => {
**Необходимо исправить**
Данная функция относится к экшену, а не к редьюсеру

2023-05-26 15:44 UTC, andreyosintsev commented
Добрый день. Я постарался устранить все замечания. Направляю работу на второе ревью. Спасибо!

2023-05-27 08:16 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-27 19:45 UTC, merged