2023/06/27 sprint-4/step-1 before 1st review
andreyosintsev/react-burger pull request #8
Opened 2023-06-27 15:30 UTC by andreyosintsev

Добрый день. Направляю работу на ревью. Спасибо.

2023-06-27 17:18 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Проект теперь типизирован;

### **Но есть несколько замечаний, которые нужно исправить:**

- Отметил замечания в коде;

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **После исправления всех замечаний, работа будет принята)**

2023-06-27 17:18 UTC, ArslanMustafin commented on src/utils/locale.ts
> +export const stubText2: string = `Булочки без начинки - это невкусно! Добавьте начинку и соусы,
**Надо исправить:**

константы принято записывать в `UPPER_CASE`

2023-06-27 17:18 UTC, ArslanMustafin commented on src/utils/burger-api.ts
> +const checkSuccess = (data: any): Promise<any> => {
**Можно лучше:**

Тут вместо `any` лучше использовать дженерики

2023-06-27 17:18 UTC, ArslanMustafin commented on src/utils/burger-api.ts
> +const request = (endpoint: string, options?: TRequestOptions): Promise<any> => {
**Можно лучше:**

Тут вместо `any` лучше использовать дженерики

2023-06-27 17:18 UTC, ArslanMustafin commented on src/utils/burger-api.ts
> +export const getIngredientsFromApi = (): (Promise<any> | void) => {
**Надо исправить:**

Здесь и далее.

Вы точно знаете что придёт с сервера, поэтому вы не должны использовать `any`. Опишите структуру которая идёт с сервера.

2023-06-27 17:18 UTC, ArslanMustafin commented on src/utils/burger-api.ts
> +  } catch (error: any) {
**Надо исправить:**

Лучше создать общий тип для ошибок.

2023-06-27 17:18 UTC, ArslanMustafin commented on src/components/app/app.tsx
> +type TAppDispatch = ThunkDispatch<TState, any, AnyAction>;
**Можно лучше:**

Здесь и во всех местах.
Типизировать redux лучше следующим образом: https://redux.js.org/usage/usage-with-typescript#define-root-state-and-dispatch-types

2023-06-27 17:18 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.tsx
> +  const showIngredientDetails = (e: any) => {
**Надо исправить:**

Вы должны типизировать `event` в обработчике событий. Если у вас возникли с этим сложности, то обратитесь к наставнику.

2023-06-27 17:18 UTC, ArslanMustafin commented on src/components/burger-section/burger-section.tsx
> +  onShowDetails: (args: any) => void;
**Надо исправить:**

Вы должны типизировать `event` в обработчике событий. Если у вас возникли с этим сложности, то обратитесь к наставнику.

2023-06-27 17:18 UTC, ArslanMustafin commented on src/hooks/useForm.ts
> +}
**Надо исправить:**

Тут не должно быть значений `any`, используйте дженерики и типизируйте функции.

2023-06-28 15:28 UTC, andreyosintsev commented on src/utils/burger-api.ts
> +const checkSuccess = (data: any): Promise<any> => {
Не идей, как можно типизировать const checkSuccess = (data: any): Promise<any>

Нужна помощь или подсказка.

2023-06-28 15:29 UTC, andreyosintsev commented on src/utils/burger-api.ts
> +  } catch (error: any) {
Через старшего куратора в Пачке Анастасию Выгузову получил от вас уточнение, что этот момент можно пропустить.

2023-06-28 15:34 UTC, andreyosintsev commented
Добрый день. Направляю работу на второе ревью. Уточнил пару моментов в комментариях выше. Спасибо.

2023-06-28 20:01 UTC, ArslanMustafin commented on src/utils/burger-api.ts
> +const checkSuccess = (data: any): Promise<any> => {
```js
const checkSuccess = (data:any) => {
  return data && data.success ? data : Promise.reject(`Ошибка Fetch не success: ${data}`);
};
```

Тут думаю можно `any` пока оставить. Этот конечно не очень хорошо, но быстро решение (Адекватное) придумать не могу))

2023-06-28 20:02 UTC, ArslanMustafin commented on src/utils/burger-api.ts
> +  } catch (error: any) {
Верно) тут я немного ошибся, так что можно пропустить))

2023-06-28 20:06 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-06-28 20:06 UTC, ArslanMustafin commented on src/hooks/useForm.ts
> +export function useForm(inputValues: TUseFormInput = {}): TUseForm {
**Можно лучше:**

тут можно воспользоваться дженериками, а также типом `React.ChangeEvent<HTMlInputElement>`.

```js
export function useForm<T>(inputValues: T) {

    const [values, setValues] = useState<T>(inputValues);

    const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
      const {value, name} = event.target;
      setValues({...values, [name]: value});
    };

    return {values, handleChange, setValues};

}

// как использовать (точно также как вы и до этого пользовались, просто чуток прибавятся типы):

type FormStateType = {
  name:string;
  password:string;
}

const initialFormState: FormStateType = {
  name: 'name',
  password: '',
}

const {...} = useForm<FormDataType>(initialFormState)
```

2023-07-05 15:02 UTC, merged